services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rizkiardianto/iot-pga-survey-fe
    container_name: iot-survey-pga-fe
    restart: always
    ports:
      - 4182:80
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - rizki-app-network

networks:
  rizki-app-network:
    driver: bridge
